### ISSUE TITLE
Not working on Android emulator or device

### ISSUE THREAD

**Issue by erjdriver** [msywensky/nativescript-phone#11] opened 2016-09-04 18:28 UTC
If i call phone.dial( "2125551212", false) - that works - the dialer pops up with the right tel#.

If I call without the 2nd parameter as true - it returns false - I can't look at the exception because it's trapped in the module.

I'm trying this in a {N} project with typescript. I've edited the master manifest file and added 3 permissions.

```
<uses-permission android:name="android.permission.CALL_PHONE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.SEND_SMS"/>
```

**Comment by devna13** [comment] 2016-11-01 17:59
I have same problem

**Comment by bradmartin** [comment] 2016-11-01 18:18
I've not reproduced this, works fine on my geny emulators with android 4.4, 5.1, 6.0 and my phone running 6.0 - either one of you want to package up a .zip of your app to look at?

**Comment by NgSculptor** [comment] 2016-11-16 20:41
+1 not working for me as well with `"nativescript-phone": "1.2.3",`

**Comment by bradmartin** [comment] 2016-11-18 16:54
![nativephone](https://cloud.githubusercontent.com/assets/6006148/20438360/fabe746a-ad7c-11e6-97fe-30979aca36a7.gif)

I just tested this and everything still seems to work for me. I'm using GenyMotion for emulator (maybe the stock Android has an issue with the phone service, I haven't tested that). It also works the same on my phone. I'm going to close this and if anyone has a specific error to test or can send a sample project to see what's happening I'll test that and give feedback. Feel free to open a new issue with details on any errors, the package.json for your project and the important bits of code related to the plugin usage.

**Closed by bradmartin** 2016-11-18 16:54 UTC

**Comment by bradmartin** [comment] 2016-11-18 18:53
Just realized are you all using android 6.0, I forgot to test that but no
there is an issue with permissions and I'll get a fix for it soon.

**Comment by RyanSMurphy** [comment] 2017-02-10 16:53
is there a fix for this, because this is an issue. Works on emulator, but not on device
